# Generated by Django 4.2.2 on 2023-11-22 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_remove_work_image_work_created_at_workimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='work',
            new_name='name',
        ),
        migrations.AddField(
            model_name='work',
            name='slug',
            field=models.SlugField(default='slug', unique=True),
        ),
    ]
