# Generated by Django 4.2.7 on 2023-12-01 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_rename_work_work_name_work_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='image',
            field=models.ImageField(default='defaultwork.png', upload_to='works'),
        ),
        migrations.DeleteModel(
            name='WorkImage',
        ),
    ]
