# Generated by Django 4.2.2 on 2023-11-21 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=50, verbose_name='Phone')),
                ('address', models.TextField(max_length=2000, verbose_name='Address')),
                ('mail', models.TextField(max_length=2000, verbose_name='E-mail')),
                ('open', models.TextField(max_length=2000, verbose_name='Open')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contact',
            },
        ),
    ]
