# Generated by Django 4.2.7 on 2023-11-18 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'about', 'verbose_name_plural': 'about'},
        ),
    ]
